language: node_js

node_js:
  - "0.12"
  - "0.10.30"

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -qq libotr2-dev"
  - "pushd test; make build LIBOTR_DIR=/usr; popd"

script:
  - "make all"
